// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_xDMO9FJmTdOxALwr92JC87yQ63aGvS0',
    appId: '1:175244524194:web:4967d4f11612a3ec9235fb',
    messagingSenderId: '175244524194',
    projectId: 'medicineapp-a6c60',
    authDomain: 'medicineapp-a6c60.firebaseapp.com',
    storageBucket: 'medicineapp-a6c60.appspot.com',
    measurementId: 'G-G0T8HX4CL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF1MqemIC75_oVohYb_upozDtZCEfAeYI',
    appId: '1:175244524194:android:e5c18c9d02d61b1b9235fb',
    messagingSenderId: '175244524194',
    projectId: 'medicineapp-a6c60',
    storageBucket: 'medicineapp-a6c60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3gt2SnhmZVz6VdrMkxhkEnYFzGLIZ95U',
    appId: '1:175244524194:ios:c77558493608c84a9235fb',
    messagingSenderId: '175244524194',
    projectId: 'medicineapp-a6c60',
    storageBucket: 'medicineapp-a6c60.appspot.com',
    iosClientId: '175244524194-2n2sb0sq513as20knlg4b6m1s6hr5eor.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3gt2SnhmZVz6VdrMkxhkEnYFzGLIZ95U',
    appId: '1:175244524194:ios:c77558493608c84a9235fb',
    messagingSenderId: '175244524194',
    projectId: 'medicineapp-a6c60',
    storageBucket: 'medicineapp-a6c60.appspot.com',
    iosClientId: '175244524194-2n2sb0sq513as20knlg4b6m1s6hr5eor.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineApp',
  );
}
